import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Qentrax for Advertisers — Buy Qualified Consumer Demand",description:"Build, fund and optimize consumer-demand campaigns with real-time filtering, Q-Shield quality controls and delivery into your existing workflow."};
export default function AdvertiserPage(){return <main className="advPage">
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <nav className="advNav shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><div><Link href="/publisher">Publishers</Link><a href="#campaigns">Campaigns</a><a href="#quality">Quality</a><a href="#integrations">Integrations</a><a href="#reporting">Reporting</a><a href="#faq">FAQ</a></div><a className="advNavCta" href="/#network">REGISTER　↗</a></nav>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advHero shell"><div><p><b/> QENTRAX FOR ADVERTISERS</p><h1>Demand that fits.<br/><em>Control that scales.</em></h1><p className="advLede">Build campaigns around the exact consumer opportunities your team can convert. Qentrax verifies, scores, bids and routes every transaction in real time.</p><aside><a className="primary" href="/#network">REGISTER AS AN ADVERTISER　↗</a><Link href="/advertiser/dashboard-preview">EXPLORE THE DASHBOARD</Link></aside><small>NO PLATFORM MIGRATION　·　FUND WHEN YOU LAUNCH　·　PAY FOR ACCEPTED OPPORTUNITIES</small></div><div className="advDecision"><header><span><b/> CAMPAIGN / LIFE-CA-04</span><strong>LIVE</strong></header><div className="advScore"><i><b>94</b><small>Q-SCORE</small></i><div><span>IDENTITY <b>96</b></span><span>INTENT <b>91</b></span><span>CONSENT <b>100</b></span><span>BUYER FIT <b>89</b></span></div></div><section><span>CALIFORNIA</span><span>AGE 35–64</span><span>LIFE INSURANCE</span></section><footer><span>DECISION</span><b>ACCEPT & DELIVER</b><strong>$61.20</strong></footer></div></section>
 <div className="advTicker"><span>REAL-TIME PING/POST</span><span>Q-SHIELD™ FILTERING</span><span>BUYER-SPECIFIC RULES</span><span>CRM & DIALER DELIVERY</span><span>CLOSED-LOOP FEEDBACK</span></div>
 <section className="advOverview shell"><header><label>THE ADVERTISER WORKSPACE</label><h2>Everything between your<br/>buying rules and revenue.</h2><p>One command center for campaigns, quality, delivery, billing and outcomes.</p></header><div className="advDashboardFrame"><div className="adfSide"><b>Q</b>{["⌂","◎","◇","⇄","$","▦"].map(x=><i key={x}>{x}</i>)}</div><div className="adfMain"><header><div><small>DEMAND COMMAND</small><h3>Good morning, Atlas Growth.</h3></div><button>＋ NEW CAMPAIGN</button></header><section>{[["$18,420","AVAILABLE BALANCE"],["$42,680","SPEND / 30D"],["1,846","ACCEPTED LEADS"],["$23.12","AVG. CPL"]].map(x=><span key={x[1]}><small>{x[1]}</small><b>{x[0]}</b></span>)}</section><div className="adfChart"><header>CAMPAIGN PERFORMANCE <small>30 DAYS</small></header><svg viewBox="0 0 800 210" preserveAspectRatio="none"><path d="M0 180 C70 170 100 100 175 125 S290 150 350 85 S475 105 535 55 S650 92 710 40 S770 60 800 22"/><path className="fill" d="M0 180 C70 170 100 100 175 125 S290 150 350 85 S475 105 535 55 S650 92 710 40 S770 60 800 22 L800 210 L0 210Z"/></svg></div></div></div><Link className="previewLink" href="/advertiser/dashboard-preview">OPEN FULL DASHBOARD PREVIEW ↗</Link></section>
 <section className="advCampaigns" id="campaigns"><div className="shell"><header><div><label>01 / CAMPAIGN CONTROL</label><h2>Build the campaign<br/>your operation can handle.</h2></div><p>Define exactly what enters your funnel—and let the marketplace adapt to your live economics and capacity.</p></header><div className="advFeatureGrid"><article><span>01</span><h3>Audience and eligibility</h3><p>Set geography, consumer attributes, product fit, evidence, exclusions and preferences.</p><b>CONFIGURABLE ↗</b></article><article><span>02</span><h3>Bids, budgets and caps</h3><p>Control price and pacing by campaign, market, source, schedule and live budget.</p><b>CONFIGURABLE ↗</b></article><article><span>03</span><h3>Schedules and capacity</h3><p>Match buying to call-center hours, agent availability and changing demand.</p><b>CONFIGURABLE ↗</b></article><article><span>04</span><h3>Delivery and ownership</h3><p>Route opportunities to the correct endpoint, team, queue or owner.</p><b>CONFIGURABLE ↗</b></article></div></div></section>
 <section className="advQuality shell" id="quality"><div><label>02 / Q-SHIELD™ QUALITY</label><h2>Every acceptance<br/>comes with evidence.</h2><p>Qentrax evaluates contact integrity, consent, duplication, behavior and buyer fit before your campaign pays for the opportunity.</p><div className="advChecks">{["Identity and contact validation","Consent proof and provenance","Network duplicate suppression","Velocity and anomaly detection","Buyer-specific eligibility","Traceable decision reasons"].map(x=><span key={x}><b>✓</b>{x}</span>)}</div></div><div className="advLedger"><header>Q-SHIELD / EVIDENCE LEDGER <b>PROTECTED</b></header>{[["IDENTITY","VERIFIED","96"],["CONSENT PROOF","ATTACHED","100"],["DUPLICATION","CLEAR","98"],["BUYER FIT","QUALIFIED","89"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><strong>{x[2]}</strong></p>)}<footer>DECISION TRACE · 14MS · IMMUTABLE</footer></div></section>
 <section className="advIntegrations" id="integrations"><div className="shell"><header><label>03 / INTEGRATIONS</label><h2>Fits the stack you already run.</h2><p>Keep your CRM, dialer and sales process. Qentrax becomes the verification and routing layer in front of them.</p></header><div className="advIntegrationFlow"><div><span>QENTRAX DECISION</span><b>VERIFY → SCORE → MATCH</b></div><i>→</i><div className="advCore"><b>YOUR WORKFLOW</b><small>CRM · DIALER · AUTOMATION</small></div><i>→</i><div><span>CLOSED LOOP</span><b>DISPOSITION FEEDBACK</b></div></div><div className="advTools">{["Salesforce","HubSpot","Zapier","Make","n8n","Webhooks","Dialers","Custom API"].map(x=><span key={x}>{x}</span>)}</div></div></section>
 <section className="advReporting shell" id="reporting"><header><div><label>04 / REPORTING</label><h2>See cost, quality and<br/>outcome in one place.</h2></div><p>Track accepted volume, spend, Q-Score, rejects, returns and disposition feedback without stitching five systems together.</p></header><div className="advReportCards">{[["SPEND","Live media balance and campaign-level cost"],["QUALITY","Q-Score trends, reject reasons and source patterns"],["OUTCOMES","Contact, sale and feedback rates by campaign"]].map(x=><article key={x[0]}><label>{x[0]}</label><p>{x[1]}</p></article>)}</div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advSteps shell" id="start"><div><label>05 / GET STARTED</label><h2>Launch without rebuilding<br/>your operation.</h2><p>Register, configure your first campaign, connect delivery and fund when you are ready to buy.</p></div><div>{[["01","Create account","Tell us your verticals, volume and current workflow."],["02","Configure campaign","Set targeting, bids, caps and acceptance rules."],["03","Connect delivery","Map CRM fields, webhooks or call endpoints."],["04","Go live","Fund the campaign and start accepting opportunities."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><a className="primary" href="/#network">REGISTER AS AN ADVERTISER　↗</a></section>
 <section className="advFaq shell" id="faq"><div><label>06 / FAQ</label><h2>Common questions from<br/>buying teams.</h2></div><div>{[["Do I need to replace my CRM?","No. Qentrax is designed to sit in front of your existing stack and deliver accepted opportunities into the tools your team already uses."],["When do I pay?","You fund campaigns and are billed for accepted opportunities according to your campaign rules and commercial terms."],["Can I enforce custom filters?","Yes. Geo, schedule, caps, exclusions, product criteria and endpoint-specific rules can all be configured per campaign."],["How fast is delivery?","Accepted opportunities can be routed to API, webhook, CRM or call destinations in milliseconds after the decision."],["What if quality issues appear?","Returns, disputes and disposition feedback flow back into the network so routing and source performance can improve over time."]].map(x=><article key={x[0]}><button type="button"><span>{x[0]}</span><b>＋</b></button><p>{x[1]}</p></article>)}</div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advFinal"><div className="shell"><label>READY TO BUY BETTER DEMAND?</label><h2>Put control between consumer intent and your sales team.</h2><div><a className="primary" href="/#network">REGISTER AS AN ADVERTISER　↗</a><Link href="/advertiser/dashboard-preview">EXPLORE THE DASHBOARD</Link></div></div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <footer className="advFooter sitefoot shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><p>The AI-native marketplace for consumer demand.</p><div><a href="#platform">Platform</a><a href="/#case-studies">Case Studies</a><Link href="/blog">Blog</Link><a href="/#about">About</a><a href="/#contact">Contact</a></div><small>© 2026 QENTRAX, INC. · ALL SYSTEMS OPERATIONAL</small></footer>
</main>}
