import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

type Article={category:string;read:string;title:string;description:string;intro:string;sections:{heading:string;body:string[]}[]};

const articles:Record<string,Article>={
 "quality-stack":{category:"Q-SHIELD / LEAD QUALITY",read:"11 MIN",title:"The new quality stack: from validation to evidence.",description:"Why modern consumer-demand quality requires identity, provenance, behavior, eligibility and outcome evidence working as one system.",intro:"A valid phone number is useful. It is not a quality strategy. High-performing demand programs treat quality as a chain of evidence that begins before a bid and continues through the final disposition.",sections:[{heading:"Validation is only the first gate",body:["Phone, email and identity checks answer a narrow question: can this contact data plausibly belong to a real person? They do not establish why the consumer appeared, whether consent is usable, whether the opportunity fits a buyer, or whether the source repeatedly produces outcomes.","The stronger model layers validation with provenance, consent, behavioral signals, duplication history and buyer-specific eligibility before money changes hands."]},{heading:"Quality is contextual",body:["The same consumer record can be valuable to one buyer and unusable to another. Geography, product, operating hours, caps, exclusions and economics all change the answer. Quality therefore has to include buyer fit—not just a universal score."]},{heading:"Evidence should survive the transaction",body:["A quality decision becomes more useful when its evidence travels with the opportunity. Source, timestamps, consent context, validation events and routing decisions create a trace that buyers can review and publishers can learn from."]},{heading:"Close the loop",body:["The final layer is outcome data. Contact, qualification, appointment, sale and rejection signals should flow back into routing and source decisions. That turns quality from a one-time filter into a learning system."]}]},
 "lead-validation":{category:"LEAD QUALITY",read:"8 MIN",title:"Why single-point lead validation is no longer enough",description:"Fraud is a pattern, not a field. Learn why network-level signals reveal risk isolated checks miss.",intro:"A lead can pass a phone check, an email check and even an identity check while still being low-value, duplicated or generated through suspicious behavior. The problem is not that validation is useless. The problem is treating one validation event as the whole answer.",sections:[{heading:"Fraud appears in relationships",body:["Repeated devices, unusual velocity, recycled contact details, source concentration and cross-campaign duplication become visible when events are evaluated together. A field-by-field approach misses those relationships."]},{heading:"Add provenance and behavior",body:["Where an opportunity came from, when it was created, how often related identifiers appear and whether its behavior resembles successful demand all matter. These signals should complement—not replace—basic contact validation."]},{heading:"Make the decision buyer-aware",body:["A technically valid record can still violate geography, product, schedule or campaign rules. Validation should feed a broader acceptance decision that includes the buyer's actual operating constraints."]}]},
 "consent-trail":{category:"COMPLIANCE / CONSENT",read:"6 MIN",title:"Building a consent trail buyers can actually use",description:"The source, timestamp, disclosure and delivery evidence that should travel with every consumer opportunity.",intro:"Consent becomes operationally useful when a buyer can understand what happened without reconstructing the consumer journey from scattered systems. The goal is a durable evidence trail attached to the opportunity.",sections:[{heading:"Capture context, not just a boolean",body:["A consent=true field says almost nothing by itself. Preserve the source, timestamp, disclosure context and relevant capture metadata so downstream teams can evaluate the evidence they received."]},{heading:"Keep evidence connected",body:["When records move through enrichment, bidding and routing, consent evidence should remain associated with the same opportunity. Separating the evidence from the transaction creates avoidable ambiguity."]},{heading:"Design for review",body:["Compliance and operations teams need an understandable event history. A traceable sequence of intake, validation, bid, route and delivery events makes investigation and reconciliation dramatically easier."]}]},
 "closed-loop-revenue":{category:"WORKFLOWS",read:"7 MIN",title:"Closing the loop between lead delivery and revenue",description:"How disposition feedback makes routing, pricing and source optimization measurably smarter over time.",intro:"Delivery is not the finish line. If the marketplace never learns what happened after a lead reached a buyer, it is optimizing against incomplete information.",sections:[{heading:"Delivery data is not outcome data",body:["An HTTP 200 can confirm receipt. It cannot tell you whether the consumer answered, qualified, booked or purchased. Those downstream events are where economic quality becomes visible."]},{heading:"Normalize dispositions",body:["Different buyers use different CRM stages and rejection reasons. Mapping those signals into a consistent vocabulary makes source and routing performance comparable across the network."]},{heading:"Feed outcomes back into decisions",body:["When outcome data returns quickly, routing can favor sources and buyer matches that produce stronger results—not merely those that accept more records. Publishers also receive feedback they can actually use to improve acquisition."]}]},
 "insurance-eligibility-rules":{category:"INSURANCE",read:"9 MIN",title:"Designing eligibility rules before the first bid",description:"A practical framework for state, product, age, consent and buyer-appetite rules in insurance demand.",intro:"Insurance demand becomes expensive when eligibility is evaluated after acquisition. The better architecture expresses the buyer's acceptance logic before bidding so unsuitable opportunities can be identified early.",sections:[{heading:"Start with hard constraints",body:["State availability, product eligibility, age ranges and other non-negotiable campaign requirements should be explicit. These rules determine whether an opportunity can enter the auction at all."]},{heading:"Separate eligibility from preference",body:["A buyer may accept a broad segment but value portions of it differently. Keeping hard exclusions separate from bid preferences allows pricing to reflect appetite without confusing preference with qualification."]},{heading:"Version the rules",body:["Buyer appetite changes. Rules should be attributable to the campaign configuration that was active when the decision occurred, making later reconciliation and analysis possible."]}]},
 "solar-lead-routing":{category:"HOME SERVICES / SOLAR",read:"7 MIN",title:"The solar routing problem is really five problems",description:"Territory, utility market, property fit, capacity and duplicate suppression must resolve in one decision.",intro:"Solar routing looks simple until a homeowner can be technically valid and still be impossible—or uneconomic—for a particular installer to serve. Several constraints have to resolve at the same moment.",sections:[{heading:"Territory is only the beginning",body:["ZIP and state coverage establish a basic service boundary, but utility market, property characteristics and campaign-specific homeowner requirements can materially change buyer fit."]},{heading:"Capacity changes in real time",body:["A buyer that wants a market this morning may hit a daily cap this afternoon. Routing should consider current capacity and operating rules rather than relying on a static buyer list."]},{heading:"Duplicates distort economics",body:["Repeated distribution wastes buyer attention and damages publisher economics. Duplicate suppression should happen before bidding wherever possible, using appropriate identifiers and time windows."]},{heading:"One decision, multiple signals",body:["The practical solution is a decision layer that resolves territory, property fit, capacity, duplication and price together, then returns a clear route or rejection reason."]}]},
 "transparent-dispositions":{category:"MARKETPLACE",read:"5 MIN",title:"Why transparent dispositions improve both sides of demand",description:"Publishers need actionable feedback and buyers need accountability. A shared disposition model aligns the market.",intro:"A marketplace works better when acceptance is not a black box. Publishers need to understand why demand succeeds or fails, while buyers need consistent ways to communicate quality and outcomes.",sections:[{heading:"Rejection reasons are market data",body:["A generic rejected status teaches nobody anything. Structured reasons—duplicate, geography, eligibility, invalid contact or cap—let publishers correct sources and let the marketplace identify systemic problems."]},{heading:"Feedback improves pricing",body:["When acceptance and downstream outcomes can be tied back to source and campaign, price becomes better informed. Stronger demand can earn more while persistent quality problems become visible sooner."]},{heading:"Transparency creates accountability",body:["A shared event trail reduces disputes because both sides can see the important decision points. The objective is not perfect agreement; it is a common factual record of what the system did and why."]}]}
};

export function generateStaticParams(){return Object.keys(articles).map(slug=>({slug}));}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=articles[slug];if(!a)return {};return {title:`${a.title} | Qentrax Field Notes`,description:a.description};}

export default async function ArticlePage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const article=articles[slug];if(!article)notFound();return <main className="blogPage">
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <nav className="blogNav shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><div><Link href="/">Marketplace</Link><Link href="/blog">Field Notes</Link><a href="/#company">Company</a><a href="/#contact">Contact</a></div><a className="blogNavCta" href="/#network">ENTER NETWORK ↗</a></nav>
 <article className="shell" style={{maxWidth:900,paddingTop:90,paddingBottom:120}}>
  <Link href="/blog" style={{font:"10px var(--mono)",letterSpacing:'.12em',color:"var(--acid)"}}>← ALL FIELD NOTES</Link>
  <header style={{padding:"50px 0 55px",borderBottom:"1px solid var(--line)"}}><label>{article.category} · {article.read} READ</label><h1 style={{fontSize:"clamp(48px,6vw,78px)",maxWidth:850}}>{article.title}</h1><p className="lede">{article.description}</p><p style={{font:"9px var(--mono)",color:"#718287",marginTop:28}}>QENTRAX RESEARCH · AUGUST 2026</p></header>
  <div style={{maxWidth:720,margin:"55px auto 0"}}><p style={{fontSize:21,lineHeight:1.7,color:"#c8d1cf",marginBottom:55}}>{article.intro}</p>{article.sections.map((s,i)=><section key={s.heading} style={{padding:"38px 0",borderTop:"1px solid var(--line)"}}><label>0{i+1} / FIELD NOTE</label><h2 style={{fontSize:"clamp(30px,4vw,44px)"}}>{s.heading}</h2>{s.body.map(p=><p key={p} style={{fontSize:16,lineHeight:1.85,color:"#9daaad"}}>{p}</p>)}</section>)}</div>
  {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
  <aside style={{marginTop:70,padding:"45px",background:"var(--acid)",color:"#071014"}}><label style={{color:"#071014"}}>QENTRAX DEMAND EXCHANGE</label><h2>Put the intelligence into the transaction.</h2><p style={{maxWidth:650,lineHeight:1.65}}>Connect as a buyer or publisher and bring validation, buyer-fit rules, routing and feedback into one demand workflow.</p><a className="dark" href="/#network" style={{display:"inline-flex",marginTop:15}}>ENTER THE NETWORK ↗</a></aside>
 </article>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <footer className="blogFooter sitefoot shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><p>The AI-native marketplace for consumer demand.</p><div><Link href="/blog">Blog</Link><a href="/#company">Company</a><a href="/#contact">Contact</a></div><small>© 2026 QENTRAX, INC. · ALL SYSTEMS OPERATIONAL</small></footer>
 </main>}
