import Link from "next/link";

const markets=[
 ["01","⌂","Real estate","Buyer, seller, investor and property inquiry opportunities routed by location, intent and timeframe.","BUYER · SELLER · INVESTOR"],
 ["02","◇","Insurance","Consumer demand across protection products, matched against geography, eligibility and buyer appetite.","AUTO · LIFE · HOME · HEALTH"],
 ["03","▦","Mortgage","Purchase, refinance and home-equity interest filtered by borrower profile and campaign criteria.","PURCHASE · REFI · HELOC"],
 ["04","§","Legal","Case inquiries evaluated for practice-area fit, jurisdiction, timing and intake requirements.","PI · MASS TORT · CONSUMER"],
 ["05","⌁","Home services","Project-ready homeowners connected to qualified providers based on service need and coverage area.","SOLAR · ROOFING · HVAC · WINDOWS"],
 ["06","$","Finance","Borrowers and business owners matched to lending programs by intent, profile and product criteria.","PERSONAL LOANS · BUSINESS LOANS"]
];
const shield=[
 ["01","IDENTITY","Contact integrity","Phone, email, address and carrier signals are normalized and checked for validity before bidding begins.","VALIDATE"],
 ["02","CONSENT","Proof attached","Consent metadata, source, timestamp and disclosure context travel with the opportunity for traceable review.","VERIFY"],
 ["03","FRAUD GRAPH","Patterns exposed","Velocity, duplication, device and behavioral anomalies are evaluated across the network—not in isolation.","DETECT"],
 ["04","BUYER FIT","Rules enforced","Geo, schedule, caps, exclusions, economics and custom acceptance logic determine the optimal destination.","ROUTE"]
];
const connectors=[["↯","Real-time delivery","REST API, ping/post and configurable webhooks deliver accepted opportunities in milliseconds."],["⌘","CRM-ready mapping","Map Qentrax data into your existing objects, fields, owners, campaigns and lead statuses."],["☎","Call routing","Send qualified calls and contact records into dialers, queues and call-center workflows."],["↻","Closed-loop feedback","Return dispositions, sales outcomes and rejects to continuously improve routing decisions."],["◇","Automation layer","Trigger notifications and downstream workflows through Zapier, Make, n8n, email, SMS or Slack."],["▦","Flexible transfer","Support secure batch delivery and scheduled exports when real-time delivery is not required."]];
const intelligenceSignals=[
 ["01","IDENTITY + CONTACT","Normalize and verify phone, email, address, carrier and identity signals."],
 ["02","CONSENT PROVENANCE","Attach source, disclosure context, timestamp and evidence for traceable review."],
 ["03","DUPLICATE CONTROL","Suppress repeated demand within configurable source, campaign and network windows."],
 ["04","FRAUD + VELOCITY","Evaluate device, behavior, repetition and submission-rate anomalies."],
 ["05","BUYER ELIGIBILITY","Apply geography, product, schedule, cap, exclusion and endpoint rules per buyer."],
 ["06","INTENT + QUALITY","Score declared intent and observed quality signals without replacing buyer judgment."],
 ["07","BID + ROUTE","Compare eligible bids and delivery constraints in real time."],
 ["08","OUTCOME FEEDBACK","Use contact, qualification, sale, cancellation and refund events to close the loop."],
 ["09","DECISION REASONS","Record Q-Shield reason codes with the permanent Qentrax transaction ID."]
];
const deploymentMetrics=["Acceptance rate","Contactability","CPA","Sales attribution","ROAS"];

export default function Home(){return <main>
 <nav className="nav shell"><a className="brand" href="#top"><i>Q</i>QENTRAX</a><div><a href="#verticals">Markets</a><Link href="/advertiser">Advertisers</Link><Link href="/publisher">Publishers</Link><a href="#security">Q-Shield</a><Link href="/blog">Intelligence</Link><a href="#company">Company</a><a href="#contact">Contact</a></div><Link href="/sign-in">ENTER NETWORK <span>↗</span></Link></nav>
 <section className="hero shell" id="top"><div><p className="eyebrow"><b/> THE DEMAND EXCHANGE IS LIVE</p><h1>Consumer demand.<br/><em>Cleared in real time.</em></h1><p className="lede">One AI-native connection to verify, enrich, bid, route and deliver high-intent consumer opportunities.</p><aside><a className="primary" href="#network">BUY OPPORTUNITIES <span>↗</span></a><a className="outline" href="#network">MONETIZE TRAFFIC</a></aside><small>✓ TCPA CONSENT PROOF　 ✓ REAL-TIME VALIDATION　 ✓ API-FIRST DELIVERY</small></div><div className="terminal"><header><span><b/> QENTRAX LIVE</span><span>US-EAST · 12MS</span></header><div className="radar"><i/><i/><strong>Q<small>ROUTING</small></strong><b/><b/><b/></div><section>{[["QL-88214","AUTO","VERIFIED","$42.80"],["QL-88215","SOLAR","3 BIDS","$68.25"],["QL-88216","LIFE","ROUTED","$31.40"],["QL-88217","HOME","VERIFIED","$54.10"]].map(r=><div key={r[0]}><code>{r[0]}</code><span>{r[1]}</span><b>{r[2]}</b><strong>{r[3]}</strong></div>)}</section><footer><span>98.7% ACCEPTED</span><span>$2.4M CLEARED / 24H</span></footer></div></section>
 <div className="ticker"><span>01　<b>VERIFY</b>　Identity, phone, email &amp; consent</span><span>02　<b>ENRICH</b>　Append intent &amp; audience data</span><span>03　<b>BID</b>　Compete in milliseconds</span><span>04　<b>ROUTE</b>　Deliver to any endpoint</span></div>
 <section className="verticals shell" id="verticals"><header><label>ACTIVE MARKETS</label><h2>High-intent demand.<br/>Across essential categories.</h2><p>One exchange, purpose-built rules. Qentrax adapts validation, compliance, scoring and delivery logic to the economics of each market.</p></header><div className="verticalGrid">{markets.map(m=><article key={m[0]}><span>{m[0]}</span><i>{m[1]}</i><h3>{m[2]}</h3><p>{m[3]}</p><small>{m[4]}</small></article>)}</div><div className="sectionFoot"><span>NEED A CUSTOM MARKET?</span><p>Qentrax rules can be configured for additional high-consideration consumer categories.</p><a href="mailto:network@qentrax.io">TALK TO THE NETWORK ↗</a></div></section>
 <section className="rolesBlock shell" id="network"><header className="splitHead"><div><label>01 / THE NETWORK</label><h2>Built for both sides<br/>of the transaction.</h2></div><p>Qentrax connects trusted demand sources to serious buyers with transparent economics, programmable controls and intelligence at every hop.</p></header><div className="roles"><article><label>FOR ADVERTISERS</label><h3>Buy outcomes,<br/>not empty clicks.</h3><p>Define exactly what you want. Set filters, bids, caps and delivery rules. Pay only for accepted opportunities.</p><ul><li>Real-time ping/post bidding</li><li>Flexible targeting &amp; bid rules</li><li>CRM, webhook &amp; call delivery</li><li>Returns and dispute controls</li></ul><Link href="/sign-in">REGISTER AS AN ADVERTISER ↗</Link></article><article><label>FOR PUBLISHERS</label><h3>Turn intent into<br/>durable revenue.</h3><p>Connect your forms, calls or traffic once. Access qualified buyers, clear pricing and automated reconciliation.</p><ul><li>One integration, multiple buyers</li><li>Live bid and disposition data</li><li>Quality feedback by source</li><li>Transparent earnings ledger</li></ul><Link href="/sign-in">REGISTER AS A PUBLISHER ↗</Link></article></div></section>
 <section className="engine"><div className="shell"><div><label>02 / INTELLIGENCE LAYER</label><h2>Every opportunity<br/>earns its route.</h2><p>Qentrax scores identity, consent, intent, duplication and buyer fit before your team ever sees the record.</p></div><div className="score"><header>OPPORTUNITY / QL-88218 <b>LIVE SCORE</b></header><section><strong>94<small>Q-SCORE</small></strong><div>{[["IDENTITY","96"],["INTENT","91"],["CONSENT","100"],["BUYER FIT","89"]].map(x=><p key={x[0]}><span>{x[0]}</span><i style={{width:`${x[1]}%`}}/><b>{x[1]}</b></p>)}</div></section><footer><span>DECISION</span><b>ACCEPT &amp; ROUTE</b><strong>$61.20</strong></footer></div></div></section>
 <section className="shield" id="security"><div className="shell"><header className="splitHead"><div><label>03 / Q-SHIELD™ FILTERING</label><h2>Bad data stops here.</h2></div><p>Our proprietary decision layer examines every opportunity across identity, consent, behavior and buyer-specific rules—then blocks, scores or routes it in milliseconds.</p></header><div className="filterFlow">{shield.map(s=><article key={s[0]}><span>{s[0]}</span><i>{s[1]}</i><h3>{s[2]}</h3><p>{s[3]}</p><b>● {s[4]}</b></article>)}</div><div className="securityGrid"><div><label>SECURITY-GRADE CONTROLS</label><h3>Protected from intake<br/>to final delivery.</h3><p>Qentrax minimizes exposure while keeping every action attributable. Sensitive lead data stays behind controlled delivery paths.</p><ul><li><strong>Tokenized identifiers</strong><span>Limit unnecessary PII exposure during matching and bidding.</span></li><li><strong>Encrypted transport</strong><span>Protected API and webhook delivery between approved endpoints.</span></li><li><strong>Role-based access</strong><span>Keep campaign, billing and lead permissions separated.</span></li><li><strong>Immutable event trail</strong><span>Trace validation, bid, route, delivery and disposition.</span></li></ul></div><div className="vault"><header><span>Q-SHIELD / EVENT TRACE</span><b>PROTECTED</b></header><div className="vaultCore"><i>Q</i><strong>TRUST ENVELOPE</strong><small>OPPORTUNITY QL-88218</small></div><section>{[["CONSENT PROOF","ATTACHED"],["PII EXPOSURE","MINIMIZED"],["ENDPOINT","AUTHORIZED"],["EVENT LEDGER","SEALED"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></p>)}</section><footer>RELEASED TO APPROVED BUYER · 14MS</footer></div></div></div></section>
 <section className="workflow"><div className="shell"><header className="splitHead"><div><label>04 / WORKFLOW INTEGRATION</label><h2>Fits the workflow<br/>you already run.</h2></div><p>Keep your CRM, dialer and sales process. Qentrax becomes the intelligence and routing layer between consumer demand and your existing revenue workflow.</p></header><div className="workflowMap"><div><small>DEMAND INPUTS</small><span>→ WEB FORMS</span><span>→ INBOUND CALLS</span><span>→ PARTNER API</span><span>→ BATCH SOURCES</span></div><div className="qLayer"><em>Q</em><strong>QENTRAX</strong><span>INTELLIGENCE LAYER</span><ul><li>FILTER</li><li>SCORE</li><li>MATCH</li><li>DELIVER</li></ul></div><div><small>YOUR EXISTING STACK</small><span>CRM ✓</span><span>DIALER / CALL CENTER ✓</span><span>MARKETING AUTOMATION ✓</span><span>DATA WAREHOUSE ✓</span></div></div><div className="connectors">{connectors.map(c=><article key={c[1]}><i>{c[0]}</i><div><h3>{c[1]}</h3><p>{c[2]}</p></div></article>)}</div></div></section>
 <section className="api shell" id="api"><div><label>05 / ONE CONNECTION</label><h2>From signal to sale<br/>in milliseconds.</h2><p>Modern APIs. Familiar workflows. Full visibility from first ping to final disposition.</p></div><pre>{`POST /v1/opportunities\n\n{\n  "vertical": "solar",\n  "consent": { "verified": true },\n  "location": { "state": "CA" },\n  "intent_score": 94\n}\n\n→ 200 ACCEPTED  $61.20`}</pre></section>
 <section className="intelligence" id="insights"><div className="shell"><header className="splitHead"><div><label>06 / QENTRAX INTELLIGENCE</label><h2>Evidence in.<br/>Accountable decisions out.</h2></div><p>The proprietary intelligence layer turns incoming demand into a scored, evidence-backed transaction. It supports operational review and buyer controls; it does not guarantee legal or regulatory compliance.</p></header><div className="trace"><header><span>TRANSACTION / QTX-2026-08-15-88218</span><b>TRACE LIVE</b></header><div className="traceFlow"><article><small>01 / INTAKE</small><strong>DEMAND SIGNAL</strong><span>Source + consent evidence</span></article><i>→</i><article><small>02 / Q-SHIELD</small><strong>VERIFY + SCORE</strong><span>Identity + quality signals</span></article><i>→</i><article><small>03 / MARKET</small><strong>ELIGIBILITY + BID</strong><span>Buyer rules + economics</span></article><i>→</i><article><small>04 / OUTCOME</small><strong>ROUTE + LEARN</strong><span>Delivery + sales feedback</span></article></div><footer><span>DECISION</span><b>ACCEPT / ROUTE</b><code>REASONS: ID_VERIFIED · CONSENT_EVIDENCE_PRESENT · BUYER_ELIGIBLE</code></footer></div><div className="signalGrid">{intelligenceSignals.map(signal=><article key={signal[0]}><span>{signal[0]}</span><label>{signal[1]}</label><p>{signal[2]}</p></article>)}</div></div></section>
 <section className="cases shell" id="deployments"><header className="splitHead"><div><label>07 / REPRESENTATIVE DEPLOYMENTS</label><h2>Configured around<br/>the way buyers operate.</h2></div><p>These illustrative scenarios show how Qentrax can be configured. They are not named-customer case studies and do not claim historical client performance.</p></header><div className="caseGrid"><article><header><label>LIFE INSURANCE ADVERTISER</label><span>REPRESENTATIVE / 01</span></header><div className="caseTitle"><i>◇</i><h3>More conversations with prospects who actually fit.</h3></div><div className="caseBody"><section><label>THE CHALLENGE</label><p>Duplicate or recycled records, inconsistent consent evidence, state, age and product-fit requirements, and limited feedback from the sales process.</p></section><section><label>QENTRAX CONFIGURATION</label><ul><li>Phone, email and identity verification</li><li>Consent evidence attached to the transaction</li><li>Buyer eligibility enforced before bidding</li><li>CRM dispositions returned for attribution</li></ul></section></div><div className="caseMetrics">{deploymentMetrics.map(metric=><span key={metric}><b>{metric}</b><small>MEASUREMENT CATEGORY</small></span>)}</div></article><article><header><label>HOME-SERVICES SOLAR ADVERTISER</label><span>REPRESENTATIVE / 02</span></header><div className="caseTitle"><i>⌁</i><h3>Route every homeowner to the right market, team and bid.</h3></div><div className="caseBody"><section><label>THE CHALLENGE</label><p>Overlapping territories, duplicate inquiries, incomplete property or utility data, and buyer capacity that changes by market and time of day.</p></section><section><label>QENTRAX CONFIGURATION</label><ul><li>Address, homeowner and service-area checks</li><li>Network-level duplicate suppression</li><li>Dynamic caps, schedules and bid controls</li><li>CRM and call-delivery outcome feedback</li></ul></section></div><div className="caseMetrics">{deploymentMetrics.map(metric=><span key={metric}><b>{metric}</b><small>MEASUREMENT CATEGORY</small></span>)}</div></article></div><p className="caseDisclosure">Illustrative deployment patterns only. Results depend on source quality, buyer rules, market conditions, sales operations and integration completeness.</p></section>
 <section className="company" id="company"><div className="shell"><div><label>08 / ABOUT QENTRAX</label><h2>Infrastructure for a more accountable demand market.</h2><p>Qentrax is an AI-native marketplace built for the teams that create, buy and convert consumer demand. We connect trusted publishers with serious advertisers, then apply intelligence to every step between first signal and final outcome.</p><div className="stats"><span><b>REAL TIME</b><small>DECISIONING</small></span><span><b>TWO-SIDED</b><small>MARKETPLACE</small></span><span><b>API FIRST</b><small>INFRASTRUCTURE</small></span></div></div><div className="mission"><label>OUR MISSION</label><h3>Make every consumer opportunity traceable, measurable and worthy of action.</h3><p>We are building the trust and intelligence layer for consumer demand—so publishers are rewarded for quality, buyers gain control, and consumers move through a more responsible ecosystem.</p></div></div></section>
 <section className="contact shell" id="contact"><div><label>08 / CONTACT THE NETWORK</label><h2>Let’s design your<br/>connection.</h2><p>Tell us whether you buy demand, generate it, or need a custom integration. Our network team will map the right path.</p><a href="mailto:network@qentrax.io">network@qentrax.io</a></div><form><div><label>YOUR NAME<input required placeholder="Full name"/></label><label>WORK EMAIL<input required type="email" placeholder="you@company.com"/></label></div><label>HOW CAN WE HELP?<textarea required rows={5} placeholder="Tell us about your goals, verticals and current workflow."/></label><button className="primary">SEND TO QENTRAX ↗</button></form></section>
 <section className="cta"><div className="shell"><label>READY TO CONNECT?</label><h2>Turn demand into accountable growth.</h2><aside><Link className="dark" href="/sign-in">ENTER NETWORK ↗</Link></aside></div></section>
 <footer className="sitefoot shell"><a className="brand" href="#top"><i>Q</i>QENTRAX</a><p>THE AI-NATIVE MARKETPLACE FOR CONSUMER DEMAND.</p><div><Link href="/advertiser">Advertisers</Link><Link href="/publisher">Publishers</Link><Link href="/blog">Field Notes</Link><a href="#security">Q-Shield</a><a href="#contact">Contact</a></div><small>© 2026 QENTRAX. ALL RIGHTS RESERVED.</small></footer>
 </main>}
