import type {Metadata} from "next";
export const metadata:Metadata={title:"Qentrax for Publishers — Monetize Qualified Consumer Demand",description:"Connect forms, calls and partner traffic to eligible buyers with validation, transparent economics and automated reconciliation."};
export default function PublisherPage(){return <main className="advPage pubPage">
 <nav className="advNav shell"><a className="brand" href="/"><i>Q</i>QENTRAX</a><div><a href="/advertiser">Advertisers</a><a href="#sources">Sources</a><a href="#quality">Quality</a><a href="#payouts">Payouts</a><a href="#integrations">Integrations</a><a href="#faq">FAQ</a></div><a className="advNavCta" href="/#network">REGISTER　↗</a></nav>
 <section className="advHero shell"><div><p><b/> QENTRAX FOR PUBLISHERS</p><h1>Traffic that clears.<br/><em>Revenue that compounds.</em></h1><p className="advLede">Connect your demand sources once. Qentrax validates, matches and routes each opportunity to eligible buyers while giving you live visibility into quality, earnings and payouts.</p><aside><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a><a href="/publisher/dashboard-preview">EXPLORE THE DASHBOARD</a></aside><small>ONE INTEGRATION　·　MULTIPLE BUYERS　·　TRANSPARENT EARNINGS</small></div><div className="advDecision"><header><span><b/> SOURCE / SOLAR-WEST-02</span><strong>LIVE</strong></header><div className="advScore"><i><b>91</b><small>Q-SCORE</small></i><div><span>IDENTITY <b>93</b></span><span>INTENT <b>88</b></span><span>CONSENT <b>100</b></span><span>MATCH <b>90</b></span></div></div><section><span>ARIZONA</span><span>HOMEOWNER</span><span>SOLAR</span></section><footer><span>STATUS</span><b>MATCHED & ROUTED</b><strong>$54.10</strong></footer></div></section>
 <div className="advTicker"><span>SOURCE VALIDATION</span><span>LIVE BID ACCESS</span><span>QUALITY FEEDBACK</span><span>AUTOMATED RECONCILIATION</span><span>FLEXIBLE PAYOUTS</span></div>
 <section className="advOverview shell"><header><label>THE PUBLISHER WORKSPACE</label><h2>See what your traffic<br/>is actually worth.</h2><p>Monitor sources, acceptance rates, earnings, rejects and payout status from one operational view.</p></header><div className="advDashboardFrame"><div className="adfSide"><b>Q</b>{["⌂","◎","◇","⇄","$","▦"].map(x=><i key={x}>{x}</i>)}</div><div className="adfMain"><header><div><small>SUPPLY COMMAND</small><h3>Source performance</h3></div><button>＋ ADD SOURCE</button></header><section>{[["$61.8K","EARNINGS / 7D"],["1,742","ACCEPTED"],["$35.48","AVG PAYOUT"],["91","AVG Q-SCORE"]].map(x=><span key={x[1]}><b>{x[0]}</b><small>{x[1]}</small></span>)}</section><div className="adfChart"><header><span>ACCEPTED VOLUME</span><b>LAST 7 DAYS</b></header><div className="adfBars">{[38,52,61,57,74,69,81].map((h,i)=><i key={i} style={{height:h+"%"}}/>)}</div></div><a className="previewLink" href="/publisher/dashboard-preview">OPEN FULL DASHBOARD PREVIEW ↗</a></div></div></section>
 <section className="advCampaigns shell" id="sources"><header><label>01 / SOURCE CONTROL</label><h2>Connect demand once.<br/>Monetize it everywhere eligible.</h2><p>Forms, calls, partner APIs and batch sources can all feed the same marketplace layer with source-level quality and economics.</p></header><div className="advFeatureGrid">{[["01","INTAKE","Web forms, inbound calls, partner posts and scheduled files"],["02","VALIDATION","Identity, consent, duplication and vertical checks at the edge"],["03","MATCHING","Eligible buyers compete according to live rules and demand"],["04","FEEDBACK","Dispositions and rejects flow back to improve source quality"]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
 <section className="advQuality shell" id="quality"><div><label>02 / QUALITY & TRUST</label><h2>Higher-quality traffic<br/>gets preferred access.</h2><p>Qentrax rewards clean consent trails, accurate data and consistent conversion feedback—not just raw volume.</p><div className="advChecks">{["Consent trail completeness","Source-level scoring","Network duplicate control","Transparent reject reasons","Disposition feedback loops","Preferred routing for quality"].map(x=><span key={x}><b>✓</b>{x}</span>)}</div></div><div className="advLedger"><header>SOURCE LEDGER <b>VISIBLE</b></header>{[["ACCEPTANCE RATE","78.4%","—"],["AVG Q-SCORE","91","—"],["TOP REJECT","CAPACITY CAP","—"],["FEEDBACK LOOP","ACTIVE","—"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><strong>{x[2]}</strong></p>)}<footer>SOURCE HEALTH · STRONG</footer></div></section>
 <section className="advIntegrations shell" id="integrations"><header><label>03 / INTEGRATIONS</label><h2>Send traffic the way<br/>you already operate.</h2><p>Use ping/post, REST, webhooks or secure batch delivery. Map fields once and keep your existing acquisition stack.</p></header><div className="advIntegrationFlow"><div><span>YOUR SOURCES</span><b>FORMS · CALLS · PARTNERS</b></div><i>→</i><div className="advCore"><b>QENTRAX</b><small>VALIDATE · MATCH · ROUTE</small></div><i>→</i><div><span>BUYER NETWORK</span><b>ACCEPTED DELIVERY</b></div></div><div className="advTools">{["Ping/Post","REST API","Webhooks","Zapier","Make","n8n","Batch CSV","Custom SFTP"].map(x=><span key={x}>{x}</span>)}</div></section>
 <section className="advReporting shell" id="payouts"><header><div><label>04 / EARNINGS & PAYOUTS</label><h2>Clear economics.<br/>Automated reconciliation.</h2></div><p>Track accepted volume, earnings, holds, returns and payout status without spreadsheet archaeology.</p></header><div className="advReportCards">{[["EARNINGS","Accepted revenue by source, vertical and day"],["RECONCILIATION","Returns, adjustments and payout-ready balances"],["PAYOUTS","Banking, tax profile and transfer schedule controls"]].map(x=><article key={x[0]}><label>{x[0]}</label><p>{x[1]}</p></article>)}</div></section>
 <section className="advSteps shell" id="start"><div><label>05 / GET STARTED</label><h2>Turn qualified demand into<br/>durable network revenue.</h2><p>Register, connect a source, pass review and start clearing opportunities against live buyer demand.</p></div><div>{[["01","Create account","Share your traffic types, verticals and monthly volume."],["02","Connect a source","Use API, form post, call webhook or batch delivery."],["03","Pass review","Qentrax validates quality, consent and operational fit."],["04","Earn","Accepted opportunities clear to buyers and accrue payouts."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a></section>
 <section className="advFaq shell" id="faq"><div><label>06 / FAQ</label><h2>Common questions from<br/>supply partners.</h2></div><div>{[["What traffic can I send?","Web forms, inbound calls, partner API posts and approved batch sources across supported consumer verticals."],["How do payouts work?","Accepted opportunities accrue earnings. Returns and adjustments are reconciled before payout-ready balances are released on your schedule."],["Do I need multiple buyer integrations?","No. One Qentrax connection can expose your traffic to multiple eligible buyers under network rules."],["How is quality measured?","Identity, consent, duplication, acceptance and disposition feedback all contribute to source health and routing preference."],["Can I see reject reasons?","Yes. Publishers get visibility into why opportunities were blocked, unmatched or returned so sources can be improved."]].map(x=><article key={x[0]}><button type="button"><span>{x[0]}</span><b>＋</b></button><p>{x[1]}</p></article>)}</div></section>
 <section className="advFinal"><div className="shell"><label>READY TO MONETIZE BETTER DEMAND?</label><h2>Connect qualified traffic to a marketplace that values proof.</h2><div><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a><a href="/publisher/dashboard-preview">EXPLORE THE DASHBOARD</a></div></div></section>
 <footer className="advFooter shell"><a className="brand" href="/"><i>Q</i>QENTRAX</a><p>THE AI-NATIVE MARKETPLACE FOR CONSUMER DEMAND.</p><div><a href="/advertiser">Advertisers</a><a href="/blog">Field Notes</a><a href="/#security">Q-Shield</a><a href="/#contact">Contact</a></div><small>© 2026 QENTRAX. ALL RIGHTS RESERVED.</small></footer>
</main>}
