import type {Metadata} from "next";
import Link from "next/link";
export const metadata:Metadata={title:"Qentrax for Publishers — Monetize Qualified Consumer Demand",description:"Connect forms, calls and partner traffic to eligible buyers with validation, transparent economics and automated reconciliation."};
export default function PublisherPage(){return <main className="advPage pubPage">
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <nav className="advNav shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><div><Link href="/advertiser">Advertisers</Link><a href="#sources">Sources</a><a href="#quality">Quality</a><a href="#payouts">Payouts</a><a href="#integrations">Integrations</a><a href="#faq">FAQ</a></div><a className="advNavCta" href="/#network">REGISTER　↗</a></nav>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advHero shell"><div><p><b/> QENTRAX FOR PUBLISHERS</p><h1>More value from<br/><em>every qualified signal.</em></h1><p className="advLede">Connect your traffic, prove its quality and reach serious buyers through one intelligent exchange. Qentrax handles validation, bidding, routing and transparent reporting in real time.</p><aside><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a><Link href="/publisher/dashboard-preview">EXPLORE THE DASHBOARD</Link></aside><small>REGISTER FIRST　·　NO OPENING BALANCE　·　PAYOUTS AFTER THE $100 THRESHOLD</small></div><div className="advDecision"><header><span><b/> SOURCE / NORTHSTAR-07</span><strong>LIVE</strong></header><div className="advScore"><i><b>92</b><small>Q-SCORE</small></i><div><span>CONTACTABILITY <b>96</b></span><span>CONSENT <b>100</b></span><span>BUYER FIT <b>89</b></span><span>SOURCE HEALTH <b>91</b></span></div></div><section><span>SOLAR</span><span>US TRAFFIC</span><span>EXCLUSIVE</span></section><footer><span>AUCTION RESULT</span><b>ACCEPTED</b><strong>$68.25</strong></footer></div></section>
 <div className="advTicker"><span>REAL-TIME PING/POST</span><span>SOURCE-LEVEL Q-SCORES</span><span>BUYER COMPETITION</span><span>COMPLIANCE EVIDENCE</span><span>TRANSPARENT EARNINGS</span></div>
 <section className="advOverview shell"><header><label>THE PUBLISHER WORKSPACE</label><h2>See what your traffic<br/>is actually worth.</h2><p>Monitor sources, acceptance rates, earnings, rejects and payout status from one operational view.</p></header><div className="advDashboardFrame"><div className="adfSide"><b>Q</b>{["⌂","◎","◇","⇄","$","▦"].map(x=><i key={x}>{x}</i>)}</div><div className="adfMain"><header><div><small>SUPPLY COMMAND</small><h3>Good morning, Northstar Media.</h3></div><button>＋ ADD SOURCE</button></header><section>{[["$31,840","EST. EARNINGS"],["$18,720","PENDING PAYOUT"],["91.4%","ACCEPTANCE RATE"],["$24.80","AVG. RPL"]].map(x=><span key={x[1]}><small>{x[1]}</small><b>{x[0]}</b></span>)}</section><div className="adfChart"><header>EARNINGS PERFORMANCE <small>30 DAYS</small></header><svg viewBox="0 0 800 210" preserveAspectRatio="none"><path d="M0 180 C70 170 100 100 175 125 S290 150 350 85 S475 105 535 55 S650 92 710 40 S770 60 800 22"/><path className="fill" d="M0 180 C70 170 100 100 175 125 S290 150 350 85 S475 105 535 55 S650 92 710 40 S770 60 800 22 L800 210 L0 210Z"/></svg></div></div></div><Link className="previewLink" href="/publisher/dashboard-preview">OPEN FULL DASHBOARD PREVIEW ↗</Link></section>
 <section className="advCampaigns" id="sources"><div className="shell"><header><div><label>01 / SOURCE CONTROL</label><h2>Connect the supply<br/>you are ready to scale.</h2></div><p>Register each traffic source, define its market and delivery method, then test it against the exchange before going live.</p></header><div className="advFeatureGrid"><article><span>01</span><h3>Source onboarding</h3><p>Register websites, funnels, call programs and acquisition channels for review.</p><b>BUILT TO SCALE ↗</b></article><article><span>02</span><h3>Flexible delivery</h3><p>Use ping/post, API, webhook, call transfer or approved batch workflows.</p><b>BUILT TO SCALE ↗</b></article><article><span>03</span><h3>Buyer competition</h3><p>Expose qualified opportunities to eligible buyers without managing separate integrations.</p><b>BUILT TO SCALE ↗</b></article><article><span>04</span><h3>Volume and pacing</h3><p>Monitor caps, acceptance and buyer demand by source, vertical and hour.</p><b>BUILT TO SCALE ↗</b></article></div></div></section>
 <section className="advQuality shell" id="quality"><div><label>02 / QUALITY & TRUST</label><h2>Higher-quality traffic<br/>gets preferred access.</h2><p>Qentrax rewards clean consent trails, accurate data and consistent conversion feedback—not just raw volume.</p><div className="advChecks">{["Consent trail completeness","Source-level scoring","Network duplicate control","Transparent reject reasons","Disposition feedback loops","Preferred routing for quality"].map(x=><span key={x}><b>✓</b>{x}</span>)}</div></div><div className="advLedger"><header>SOURCE LEDGER <b>VISIBLE</b></header>{[["ACCEPTANCE RATE","78.4%","—"],["AVG Q-SCORE","91","—"],["TOP REJECT","CAPACITY CAP","—"],["FEEDBACK LOOP","ACTIVE","—"]].map(x=><p key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><strong>{x[2]}</strong></p>)}<footer>SOURCE HEALTH · STRONG</footer></div></section>
 <section className="advIntegrations" id="integrations"><div className="shell"><header><label>03 / INTEGRATIONS</label><h2>Send traffic the way<br/>you already operate.</h2><p>Use ping/post, REST, webhooks or secure batch delivery. Map fields once and keep your existing acquisition stack.</p></header><div className="advIntegrationFlow"><div><span>YOUR SOURCES</span><b>FORMS · CALLS · PARTNERS</b></div><i>→</i><div className="advCore"><b>QENTRAX</b><small>VALIDATE · MATCH · ROUTE</small></div><i>→</i><div><span>BUYER NETWORK</span><b>ACCEPTED DELIVERY</b></div></div><div className="advTools">{["Ping/Post","REST API","Webhooks","Zapier","Make","n8n","Batch CSV","Custom SFTP"].map(x=><span key={x}>{x}</span>)}</div></div></section>
 <section className="advReporting shell" id="payouts"><header><div><label>04 / EARNINGS & PAYOUTS</label><h2>Clear economics.<br/>Automated reconciliation.</h2></div><p>Track accepted volume, earnings, holds, returns and payout status without spreadsheet archaeology.</p></header><div className="advReportCards">{[["EARNINGS","Accepted revenue by source, vertical and day"],["RECONCILIATION","Returns, adjustments and payout-ready balances"],["PAYOUTS","Banking, tax profile and transfer schedule controls"]].map(x=><article key={x[0]}><label>{x[0]}</label><p>{x[1]}</p></article>)}</div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advSteps shell" id="start"><div><label>05 / GET STARTED</label><h2>Turn qualified demand into<br/>durable network revenue.</h2><p>Register, connect a source, pass review and start clearing opportunities against live buyer demand.</p></div><div>{[["01","Create account","Share your traffic types, verticals and monthly volume."],["02","Connect a source","Use API, form post, call webhook or batch delivery."],["03","Pass review","Qentrax validates quality, consent and operational fit."],["04","Earn","Accepted opportunities clear to buyers and accrue payouts."]].map(x=><article key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a></section>
 <section className="advFaq shell" id="faq"><div><label>06 / FAQ</label><h2>Common questions from<br/>supply partners.</h2></div><div>{[["What traffic can I send?","Web forms, inbound calls, partner API posts and approved batch sources across supported consumer verticals."],["How do payouts work?","Accepted opportunities accrue earnings. Returns and adjustments are reconciled before payout-ready balances are released on your schedule."],["Do I need multiple buyer integrations?","No. One Qentrax connection can expose your traffic to multiple eligible buyers under network rules."],["How is quality measured?","Identity, consent, duplication, acceptance and disposition feedback all contribute to source health and routing preference."],["Can I see reject reasons?","Yes. Publishers get visibility into why opportunities were blocked, unmatched or returned so sources can be improved."]].map(x=><article key={x[0]}><button type="button"><span>{x[0]}</span><b>＋</b></button><p>{x[1]}</p></article>)}</div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <section className="advFinal"><div className="shell"><label>READY TO MONETIZE BETTER DEMAND?</label><h2>Connect qualified traffic to a marketplace that values proof.</h2><div><a className="primary" href="/#network">REGISTER AS A PUBLISHER　↗</a><Link href="/publisher/dashboard-preview">EXPLORE THE DASHBOARD</Link></div></div></section>
 {/* eslint-disable-next-line @next/next/no-html-link-for-pages */}
 <footer className="advFooter sitefoot shell"><Link className="brand" href="/"><i>Q</i>QENTRAX</Link><p>The AI-native marketplace for consumer demand.</p><div><a href="#platform">Platform</a><a href="/#case-studies">Case Studies</a><Link href="/blog">Blog</Link><a href="/#about">About</a><a href="/#contact">Contact</a></div><small>© 2026 QENTRAX, INC. · ALL SYSTEMS OPERATIONAL</small></footer>
</main>}
