type Role="advertiser"|"publisher"|"admin";
const configs={
 advertiser:{eyebrow:"DEMAND COMMAND",title:"Good morning, Atlas Growth.",sub:"Your campaigns cleared 286 qualified opportunities in the last 24 hours.",action:"＋ NEW CAMPAIGN",nav:["Overview","Campaigns","Opportunities","Integrations","Billing","Settings"],stats:[["$48.2K","SPEND / 7D"],["1,284","ACCEPTED"],["$37.54","AVG COST"],["94","AVG Q-SCORE"]]},
 publisher:{eyebrow:"SUPPLY COMMAND",title:"Good morning, Westline Media.",sub:"Your sources cleared 1,742 accepted opportunities in the last 7 days.",action:"＋ ADD SOURCE",nav:["Overview","Sources","Transactions","Quality","Payouts","Settings"],stats:[["$61.8K","EARNINGS / 7D"],["1,742","ACCEPTED"],["$35.48","AVG PAYOUT"],["91","AVG Q-SCORE"]]},
 admin:{eyebrow:"NETWORK OPS",title:"Network control room.",sub:"14 advertisers and 31 publishers are active across 6 verticals.",action:"＋ REVIEW QUEUE",nav:["Overview","Accounts","Quality","Ledger","Payouts","Settings"],stats:[["$2.4M","CLEARED / 24H"],["98.7%","ACCEPT RATE"],["6","VERTICALS"],["45","ACTIVE ACCOUNTS"]]}
};
const activity={
 advertiser:[["QL-88218","LIFE","94","DELIVERED","$61.20"],["QL-88219","AUTO","91","ACCEPTED","$42.80"],["QL-88221","HOME","88","PENDING","$36.40"],["QL-88224","LIFE","96","DELIVERED","$58.10"]],
 publisher:[["QL-77102","SOLAR","93","ACCEPTED","$54.10"],["QL-77105","HVAC","89","ROUTED","$41.25"],["QL-77109","SOLAR","95","ACCEPTED","$57.80"],["QL-77112","ROOF","87","RETURNED","$0.00"]],
 admin:[["FLAG-204","CONSENT","Missing timestamp","OPEN","HIGH"],["FLAG-205","DUPLICATE","Velocity spike","REVIEW","MED"],["PAY-991","PAYOUT","Publisher batch","READY","$184K"],["ACC-441","KYC","Advertiser review","WAITING","NORMAL"]]
};
export default function Dashboard({role}:{role:Role}){
 const c=configs[role];
 return <main className={`dash dash-${role}`}>
 <aside className="dashSide"><a className="dashBrand" href="/"><i>Q</i><span>QENTRAX</span></a><nav>{c.nav.map((item,i)=><button key={item} className={i===0?"active":""}>{item}</button>)}</nav><div className="dashSideFoot"><small>{c.eyebrow}</small><strong>{role.toUpperCase()}</strong></div></aside>
 <section className="dashMain">
 <header className="dashTop"><div><p>{c.eyebrow}</p><h1>{c.title}</h1><span>{c.sub}</span></div><button>{c.action}</button></header>
 <div className="dashStats">{c.stats.map(s=><article key={s[1]}><b>{s[0]}</b><small>{s[1]}</small></article>)}</div>
 <div className="dashMid"><article className="trend"><header><span>PERFORMANCE TREND</span><b>LAST 5 WEEKS</b></header><div className="chartWrap"><svg viewBox="0 0 700 230" preserveAspectRatio="none"><defs><linearGradient id={`g-${role}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={role==="publisher"?"#54eaff":"#caff4b"} stopOpacity=".35"/><stop offset="100%" stopColor={role==="publisher"?"#54eaff":"#caff4b"} stopOpacity="0"/></linearGradient></defs><path className="area" d="M0 200 C60 185 80 120 145 145 S230 178 290 100 S390 130 440 72 S540 120 590 55 S660 75 700 30 L700 230 L0 230Z" fill={`url(#g-${role})`}/><path className="line" d="M0 200 C60 185 80 120 145 145 S230 178 290 100 S390 130 440 72 S540 120 590 55 S660 75 700 30"/><g className="dots"><circle cx="145" cy="145" r="4"/><circle cx="290" cy="100" r="4"/><circle cx="440" cy="72" r="4"/><circle cx="590" cy="55" r="4"/><circle cx="700" cy="30" r="4"/></g></svg><div className="xlabels"><span>W1</span><span>W2</span><span>W3</span><span>W4</span><span>NOW</span></div></div></article>
 <article className="health"><header><span>{role==="admin"?"NETWORK HEALTH":role==="publisher"?"SOURCE HEALTH":"CAMPAIGN HEALTH"}</span><b>LIVE</b></header><div className="healthRing"><strong>{role==="admin"?"97":role==="publisher"?"91":"94"}</strong><small>HEALTH SCORE</small></div>{[["QUALITY",94],["DELIVERY",98],["COMPLIANCE",100],["FEEDBACK",87]].map(x=><p key={x[0]}><span>{x[0]}</span><i><b style={{width:x[1]+"%"}}/></i><strong>{x[1]}</strong></p>)}</article></div>
 <div className="dashLower"><article className="liveTable"><header><div><span>{role==="admin"?"OPERATOR QUEUE":"LIVE OPPORTUNITIES"}</span><h2>{role==="admin"?"Items requiring review":"Recent network activity"}</h2></div><button>VIEW ALL ↗</button></header><div className="tableHead"><span>ID</span><span>{role==="admin"?"TYPE":"VERTICAL"}</span><span>{role==="admin"?"REASON":"SCORE"}</span><span>STATUS</span><span>{role==="admin"?"PRIORITY":"VALUE"}</span></div>{activity[role].map(r=><div className="tableRow" key={r[0]}>{r.map((v,i)=><span className={i===3?"status":""} key={i}>{v}</span>)}</div>)}</article>
 <article className="quick"><header><span>QUICK ACTIONS</span><button>•••</button></header>{(role==="advertiser"?[["＋","Build a campaign","Set targeting, bids and delivery"],["$","Fund account","Add to your media balance"],["⇄","Connect CRM","Map your delivery endpoint"]]:role==="publisher"?[["＋","Add a traffic source","Begin source review"],["⇄","Connect integration","Send a test opportunity"],["$","Payout settings","Manage tax and banking"]]:[["✓","Approve accounts","8 advertisers · 6 publishers"],["⚑","Review quality flags","3 high-priority events"],["$","Release payouts","$184K ready for approval"]]).map(x=><button className="quickRow" key={x[1]}><i>{x[0]}</i><span><b>{x[1]}</b><small>{x[2]}</small></span><em>→</em></button>)}</article></div>
 </section>
 </main>}
