"use client";

import Link from "next/link";
import { useState } from "react";

type NetworkKind = "advertiser" | "publisher";

const routeContent = {
  advertiser: {
    eyebrow: "QENTRAX FOR ADVERTISERS",
    hero: ["Demand that fits.", "Control that scales."],
    intro: "Build campaigns around the exact consumer opportunities your team can convert. Qentrax verifies, scores, bids and routes every transaction in real time.",
    cta: "REGISTER AS AN ADVERTISER",
    note: "NO PLATFORM MIGRATION · FUND WHEN YOU LAUNCH · PAY FOR ACCEPTED OPPORTUNITIES",
    other: ["Publishers", "/publisher"],
    terminal: { label: "CAMPAIGN / LIFE-CA-04", score: "94", color: "acid", rows: [["IDENTITY","96"],["INTENT","91"],["CONSENT","100"],["BUYER FIT","89"]], tags: ["CALIFORNIA","AGE 35–64","LIFE INSURANCE"], result: "ACCEPT & DELIVER", value: "$61.20" },
    ticker: ["REAL-TIME PING/POST","Q-SHIELD™ FILTERING","BUYER-SPECIFIC RULES","CRM & DIALER DELIVERY","CLOSED-LOOP FEEDBACK"],
    workspace: { label: "THE ADVERTISER WORKSPACE", title: "Everything between your buying rules and revenue.", copy: "One command center for campaigns, quality, delivery, billing and outcomes.", command: "DEMAND COMMAND", greeting: "Good morning, Atlas Growth.", stats: [["AVAILABLE BALANCE","$18,420"],["SPEND / 30D","$42,680"],["ACCEPTED LEADS","1,846"],["AVG. CPL","$23.12"]] },
    controls: { label: "01 / CAMPAIGN CONTROL", title: "Build the campaign your operation can handle.", copy: "Define exactly what enters your funnel—and let the marketplace adapt to your live economics and capacity.", cards: [["Audience and eligibility","Set geography, consumer attributes, product fit, evidence, exclusions and preferences."],["Bids, budgets and caps","Control price and pacing by campaign, market, source, schedule and live budget."],["Schedules and capacity","Match buying to call-center hours, agent availability and changing demand."],["Delivery and ownership","Route opportunities to the correct endpoint, team, queue or owner."]] },
    quality: { label: "02 / Q-SHIELD™ QUALITY", title: "Every acceptance comes with evidence.", copy: "Qentrax evaluates contact integrity, consent, duplication, behavior and buyer fit before your campaign pays for the opportunity.", items: ["Identity and contact validation","Consent proof and provenance","Network duplicate suppression","Velocity and anomaly detection","Buyer-specific eligibility","Traceable decision reasons"], ledger: "Q-SHIELD / EVIDENCE LEDGER" },
    workflow: { label: "03 / YOUR WORKFLOW", title: "Keep the stack. Improve what enters it.", copy: "Qentrax connects through the tools and delivery patterns your revenue operation already uses.", left: ["CONSUMER DEMAND"], core: "FILTER · SCORE · ROUTE", right: ["CRM","DIALER","WEBHOOK","DATA"] },
    optimize: { label: "04 / OPTIMIZATION", title: "See what happens after delivery.", copy: "Connect dispositions and revenue outcomes to the exact campaign, source and opportunity that produced them.", cards: [["◎","Live lead ledger","Follow validation, bid, routing, delivery and return events in one trace."],["↻","Disposition feedback","Return contact, qualification, appointment and sale outcomes."],["▦","Source intelligence","Compare acceptance, contactability and conversion by source and market."],["↗","Reports and exports","Schedule reports, export transactions and monitor economics."]] },
    startTitle: "From registration to live demand.", steps: [["REGISTER","Create your company account and tell us what you buy."],["BUILD","Set campaign rules, bids, caps and delivery endpoints."],["TEST","Validate mappings with controlled test opportunities."],["FUND & LAUNCH","Fund the campaign when you are ready to go live."]],
    faqLabel: "ADVERTISER FAQ", faqs: [["Do I need to replace my CRM or dialer?","No. Qentrax is designed to connect with existing CRMs, dialers, webhooks and data workflows."],["When do I fund my account?","Configure and test first. Funding is required only when an eligible campaign is ready to launch, subject to the configured minimum."],["Can I control exactly what I accept?","Yes. Campaign eligibility, bids, budgets, caps, schedules and delivery rules remain buyer-specific."],["How are returns and disputes handled?","Return and dispute requests retain the original transaction history and follow the configured policy and review workflow."],["Can Qentrax use my sales outcomes?","Yes, when you connect signed webhooks, CRM events or approved imports. Outcome data is tied back to the permanent Qentrax transaction ID."]],
    finalKicker: "YOUR NEXT CAMPAIGN STARTS HERE.", finalTitle: "Buy consumer demand with evidence attached.", copyright: "ADVERTISER NETWORK"
  },
  publisher: {
    eyebrow: "QENTRAX FOR PUBLISHERS",
    hero: ["More value from", "every qualified signal."],
    intro: "Connect your traffic, prove its quality and reach serious buyers through one intelligent exchange. Qentrax handles validation, bidding, routing and transparent reporting in real time.",
    cta: "REGISTER AS A PUBLISHER",
    note: "REGISTER FIRST · NO OPENING BALANCE · PAYOUTS AFTER THE $100 THRESHOLD",
    other: ["Advertisers", "/advertiser"],
    terminal: { label: "SOURCE / NORTHSTAR-07", score: "92", color: "cyan", rows: [["CONTACTABILITY","96"],["CONSENT","100"],["BUYER FIT","89"],["SOURCE HEALTH","91"]], tags: ["SOLAR","US TRAFFIC","EXCLUSIVE"], result: "ACCEPTED", value: "$68.25" },
    ticker: ["REAL-TIME PING/POST","SOURCE-LEVEL Q-SCORES","BUYER COMPETITION","COMPLIANCE EVIDENCE","TRANSPARENT EARNINGS"],
    workspace: { label: "THE PUBLISHER WORKSPACE", title: "Everything between your traffic and your earnings.", copy: "One command center for sources, quality, integrations, transactions and payouts.", command: "SUPPLY COMMAND", greeting: "Good morning, Northstar Media.", stats: [["EST. EARNINGS","$31,840"],["PENDING PAYOUT","$18,720"],["ACCEPTANCE RATE","91.4%"],["AVG. RPL","$24.80"]] },
    controls: { label: "01 / SOURCE CONTROL", title: "Connect the supply you are ready to scale.", copy: "Register each traffic source, define its market and delivery method, then test it against the exchange before going live.", cards: [["Source onboarding","Register websites, funnels, call programs and acquisition channels for review."],["Flexible delivery","Use ping/post, API, webhook, call transfer or approved batch workflows."],["Buyer competition","Expose qualified opportunities to eligible buyers without managing separate integrations."],["Volume and pacing","Monitor caps, acceptance and buyer demand by source, vertical and hour."]] },
    quality: { label: "02 / Q-SHIELD™ SOURCE QUALITY", title: "Know why every opportunity clears.", copy: "Qentrax gives publishers source-level evidence before and after each transaction, helping you improve acceptance without guessing what buyers need.", items: ["Identity and contact validation","Consent evidence capture","Duplicate suppression","Velocity and anomaly detection","Vertical-specific eligibility","Traceable rejection reasons"], ledger: "SOURCE / QUALITY LEDGER" },
    workflow: { label: "03 / YOUR WORKFLOW", title: "Send demand your way. Qentrax handles the rest.", copy: "Connect existing funnels and lead systems without rebuilding your acquisition stack.", left: ["LANDING PAGE","CALL FLOW","LEAD FORM","CRM"], core: "VERIFY · AUCTION · ROUTE", right: ["QUALIFIED BUYERS"] },
    optimize: { label: "04 / EARNINGS & INTELLIGENCE", title: "See what clears, what pays and why.", copy: "Follow every opportunity from validation through buyer decision and payout—down to its source and transaction history.", cards: [["◎","Live transaction ledger","Track validation, bids, acceptance, routing and value in one trace."],["↻","Rejection intelligence","See buyer decision reasons and improve source quality over time."],["▦","Source analytics","Compare acceptance, revenue and quality by source, market and campaign."],["$","Payout visibility","Review pending, approved and paid balances with downloadable statements."]] },
    startTitle: "From registration to monetized demand.", steps: [["REGISTER","Create your publisher account and company profile."],["ADD SOURCES","Submit traffic sources, verticals and acquisition methods."],["TEST","Validate consent, fields and delivery through controlled tests."],["GO LIVE","Begin sending opportunities and track earnings in real time."]],
    faqLabel: "PUBLISHER FAQ", faqs: [["Do I pay anything to register?","No. Publishers do not pay to register. Each source must complete approval and controlled testing before sending live demand."],["When do publishers get paid?","Approved earnings become eligible on Net 30 terms after the configurable $100 payout threshold is reached."],["Which delivery methods are supported?","REST API, ping/post, webhooks, approved call transfers and controlled batch workflows are supported by configuration."],["Can I see why an opportunity was rejected?","Yes. Traceable Q-Shield and buyer-decision reason codes are attached to the transaction event history."],["Can I connect more than one source?","Yes. Sources are registered, reviewed, measured and controlled independently within the publisher organization."]],
    finalKicker: "YOUR NEXT SOURCE STARTS HERE.", finalTitle: "Turn qualified demand into transparent revenue.", copyright: "PUBLISHER NETWORK"
  }
} as const;

export function NetworkMarketingPage({kind}:{kind:NetworkKind}) {
  const content=routeContent[kind];
  const [openFaq,setOpenFaq]=useState<number|null>(null);
  return <main className="routePage">
    <nav className="routeNav shell"><Link className="routeBrand" href="/"><i>Q</i><span>QENTRAX</span></Link><div><Link href={content.other[1]}>{content.other[0]}</Link><a href="#controls">{kind==="advertiser"?"Campaigns":"Sources"}</a><a href="#quality">Quality</a><a href="#integrations">Integrations</a><a href="#reporting">{kind==="advertiser"?"Reporting":"Earnings"}</a><a href="#faq">FAQ</a></div><Link className="routeRegister" href="/sign-in">REGISTER ↗</Link></nav>
    <section className="routeHero shell"><div><p className="routeEyebrow"><b/> {content.eyebrow}</p><h1>{content.hero[0]}<br/><em>{content.hero[1]}</em></h1><p className="routeIntro">{content.intro}</p><aside><Link className="primary" href="/sign-in">{content.cta}　↗</Link><Link className="outline" href="/workspace">EXPLORE THE DASHBOARD</Link></aside><small>{content.note}</small></div><ScoreTerminal data={content.terminal}/></section>
    <div className="routeTicker">{content.ticker.map(item=><span key={item}>{item}</span>)}</div>
    <section className="workspaceShow shell"><header><label>{content.workspace.label}</label><div><h2>{content.workspace.title}</h2><p>{content.workspace.copy}</p></div></header><div className="dashPreview"><aside><b>Q</b>{["⌂","◎","◇","⇄","$","▦"].map(x=><span key={x}>{x}</span>)}</aside><div><label>{content.workspace.command}</label><h3>{content.workspace.greeting}</h3><div className="dashStats">{content.workspace.stats.map(x=><span key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></span>)}</div><div className="dashChart"><header>PERFORMANCE <b>30 DAYS</b></header><i/><i/><i/><i/><i/><i/></div><Link href="/workspace">OPEN FULL DASHBOARD PREVIEW　↗</Link></div></div></section>
    <section className="routeSection shell" id="controls"><header className="routeSplit"><div><label>{content.controls.label}</label><h2>{content.controls.title}</h2></div><p>{content.controls.copy}</p></header><div className="routeCards">{content.controls.cards.map((card,index)=><article key={card[0]}><span>0{index+1}</span><h3>{card[0]}</h3><p>{card[1]}</p><small>{kind==="advertiser"?"CONFIGURABLE":"BUILT TO SCALE"}　↗</small></article>)}</div></section>
    <section className="qualitySection" id="quality"><div className="shell"><header className="routeSplit"><div><label>{content.quality.label}</label><h2>{content.quality.title}</h2><p>{content.quality.copy}</p></div><ul>{content.quality.items.map(item=><li key={item}>✓ {item}</li>)}</ul></header><div className="evidenceLedger"><header><span>{content.quality.ledger}</span><b>{kind==="advertiser"?"PROTECTED":"VERIFIED"}</b></header>{[["IDENTITY","VERIFIED","96"],["CONSENT PROOF","ATTACHED","100"],["DUPLICATION","CLEAR","98"],["BUYER FIT","QUALIFIED","89"]].map(row=><p key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><strong>{row[2]}</strong></p>)}<footer><span>QL-90184</span><b>{kind==="advertiser"?"ACCEPT & ROUTE":"ACCEPTED"}</b><strong>{kind==="advertiser"?"14MS":"$68.25"}</strong></footer></div></div></section>
    <section className="routeSection shell" id="integrations"><header className="routeSplit"><div><label>{content.workflow.label}</label><h2>{content.workflow.title}</h2></div><p>{content.workflow.copy}</p></header><div className="routeWorkflow"><div>{content.workflow.left.map(x=><span key={x}>{x}</span>)}</div><i>→</i><div className="routeCore"><b>QENTRAX</b><small>{content.workflow.core}</small></div><i>→</i><div>{content.workflow.right.map(x=><span key={x}>{x}</span>)}</div></div><div className="integrationList">{["REST API","PING / POST","WEBHOOKS",kind==="advertiser"?"SALESFORCE":"CALL TRANSFER",kind==="advertiser"?"HUBSPOT":"JORNAYA","ZAPIER","MAKE","N8N","SFTP / BATCH"].map(x=><span key={x}>{x}</span>)}</div></section>
    <section className="routeSection shell" id="reporting"><header className="routeSplit"><div><label>{content.optimize.label}</label><h2>{content.optimize.title}</h2></div><p>{content.optimize.copy}</p></header><div className="optimizationGrid">{content.optimize.cards.map(card=><article key={card[1]}><i>{card[0]}</i><h3>{card[1]}</h3><p>{card[2]}</p></article>)}</div></section>
    <section className="startSection"><div className="shell"><label>05 / GET STARTED</label><h2>{content.startTitle}</h2><div className="stepGrid">{content.steps.map((step,index)=><article key={step[0]}><span>0{index+1}</span><h3>{step[0]}</h3><p>{step[1]}</p></article>)}</div><Link className="primary" href="/sign-in">{content.cta}　↗</Link></div></section>
    <section className="faqSection shell" id="faq"><label>{content.faqLabel}</label><h2>Before you connect.</h2><div>{content.faqs.map((faq,index)=><article key={faq[0]}><button type="button" aria-expanded={openFaq===index} onClick={()=>setOpenFaq(openFaq===index?null:index)}><span>{faq[0]}</span><b>{openFaq===index?"−":"＋"}</b></button>{openFaq===index&&<p>{faq[1]}</p>}</article>)}</div></section>
    <section className="routeCta"><div className="shell"><label>{content.finalKicker}</label><h2>{content.finalTitle}</h2><aside><Link className="dark" href="/sign-in">REGISTER NOW　↗</Link><Link className="outline" href="/workspace">VIEW DASHBOARD</Link></aside></div></section>
    <RouteFooter kind={kind} copyright={content.copyright}/>
  </main>
}

function ScoreTerminal({data}:{data:(typeof routeContent)[NetworkKind]["terminal"]}) {return <div className={`routeScore ${data.color}`}><header><span><b/> {data.label}</span><strong>LIVE</strong></header><section><div className="scoreRing"><b>{data.score}</b><small>Q-SCORE</small></div><div>{data.rows.map(row=><p key={row[0]}><span>{row[0]}</span><b>{row[1]}</b></p>)}</div></section><div className="scoreTags">{data.tags.map(tag=><span key={tag}>{tag}</span>)}</div><footer><span>DECISION</span><b>{data.result}</b><strong>{data.value}</strong></footer></div>}

export function RouteFooter({kind,copyright}:{kind?:NetworkKind;copyright:string}) {return <footer className="routeFooter shell"><Link className="routeBrand" href="/"><i>Q</i><span>QENTRAX</span></Link><p>The AI-native marketplace for consumer demand.</p><div><Link href="/">Home</Link>{kind==="publisher"&&<Link href="/advertiser">Advertisers</Link>}<Link href="/blog">Field Notes</Link><Link href="/#deployments">Case Studies</Link><Link href="/#contact">Contact</Link></div><small>© 2026 QENTRAX, INC. · {copyright}</small></footer>}
