db-uri = "postgres://authenticator@localhost:55432/qentrax"
db-schemas = "public"
db-anon-role = "anon"
server-port = 3001
jwt-secret = "@/home/user/Qentrax/e2e/harness/jwks.json"
jwt-role-claim-key = ".role"
db-pool = 10
