begin;
create extension if not exists pgcrypto;
create type public.organization_type as enum ('advertiser','publisher','platform');
create type public.record_status as enum ('active','suspended','closed');
create table public.users (id uuid primary key default gen_random_uuid(), auth_subject uuid not null unique, email text not null unique, display_name text not null, status public.record_status not null default 'active', last_login_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), version integer not null default 1 check(version>0));
create table public.organizations (id uuid primary key default gen_random_uuid(), type public.organization_type not null, legal_name text not null, dba_name text, website text, tax_country char(2), status public.record_status not null default 'active', onboarding_status text not null default 'draft', risk_tier text not null default 'unrated', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), version integer not null default 1 check(version>0));
create table public.roles (id uuid primary key default gen_random_uuid(), code text not null unique, name text not null, created_at timestamptz not null default now());
create table public.role_permissions (role_id uuid not null references public.roles(id), permission_code text not null, primary key(role_id,permission_code));
create table public.organization_members (id uuid primary key default gen_random_uuid(), organization_id uuid not null references public.organizations(id), user_id uuid not null references public.users(id), role_id uuid not null references public.roles(id), status public.record_status not null default 'active', invited_by uuid references public.users(id), joined_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), version integer not null default 1, unique(organization_id,user_id));
create table public.reason_codes (code text primary key check(code ~ '^[A-Z]+_[A-Z0-9_]+$'), family text not null, description text not null, active boolean not null default true, created_at timestamptz not null default now());
create table public.audit_events (id uuid primary key default gen_random_uuid(), actor_user_id uuid references public.users(id), actor_org_id uuid references public.organizations(id), action text not null, resource_type text not null, resource_id uuid, reason text, before_redacted jsonb, after_redacted jsonb, ip_hash text, request_id text not null, created_at timestamptz not null default now());
create or replace function public.active_organization_id() returns uuid language sql stable as $$ select nullif(current_setting('app.organization_id',true),'')::uuid $$;
alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;
alter table public.audit_events enable row level security;
create policy organizations_tenant_select on public.organizations for select using (id=public.active_organization_id());
create policy members_tenant_select on public.organization_members for select using (organization_id=public.active_organization_id());
create policy audit_tenant_select on public.audit_events for select using (actor_org_id=public.active_organization_id());
create or replace function public.prevent_audit_mutation() returns trigger language plpgsql as $$ begin raise exception 'audit_events are append-only'; end $$;
create trigger audit_events_immutable before update or delete on public.audit_events for each row execute function public.prevent_audit_mutation();
commit;
